name: "ci"

on:
  push:
    branches:
      - "dev"

jobs:
  kubernetes-cluster-test:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to minikube
      run: ls -lat && cd ./chart/nginx-academy && ls -lat