name: "ci"

on:
  push:
    branches:
      - "dev"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DOckerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Buidld and Push
        uses: docker/build-push-action@v3
        with: 
          file: Dockerfile
          context: .
          push: true
          tags: ignaciocolussi/nginx-academy:${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}
