name: "ci"

on:
  push:
    branches:
      - "dev"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push
        uses: docker/build-push-action@v3
        with: 
          file: Dockerfile
          context: .
          push: true
          tags: ignaciocolussi/nginx-academy:${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }}

  kubernetes-cluster-test:
    needs: [ docker-build ]
    runs-on: ubuntu-latest
    if: (github.ref == 'refs/heads/dev')
    name: kubernetes
    steps:
    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster
      run: kubectl get pods -A
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.9.0' # default is latest (stable)
      id: install
    - name: Deploy to minikube
      run:
        helm upgrade --install nginx-academy /chart/nginx-academy --values=deploy/scopes/main.yaml --set image.tag=${{ github.ref_name }}-${{ github.sha }}-${{ github.run_id }} --wait --timeout "3m0s"